### ISSUE TITLE
[BUG] Can't run tutorial demo locally

### ISSUE THREAD

**Issue by dgwyer** [stackblitz/webcontainer-docs#4]
**Describe the bug**
I'm working through the tutorial here: https://webcontainers.io/tutorial/1-building-your-first-webcontainers-app.

However, I can't get it to work due to the following console error message.

![image](https://user-images.githubusercontent.com/1482075/219003090-608ee2b8-0792-4a3c-b0cd-a48f90cd097f.png)

I've tried restarting the dev server, and hard-refreshing the browser several times.

**To Reproduce**
Just follow the current tutorial steps.

**Expected behavior**
Expected it to work the same as the [final project](https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-qj4psn?file=README.md).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 109.0.5414.120 (Official Build) (64-bit)

**Comment by SamVerschueren** [comment]
Hi @dgwyer. Have you read through the [set up COOP/COEP headers](https://webcontainers.io/tutorial/2-setting-up-webcontainers#_1-set-up-coop-coep-headers) section?

In order to use `SharedArrayBuffer` (which we heavily rely on), the page has to be cross origin isolated (like your error message indicates).

**Comment by dgwyer** [comment]
Yes, I followed all the tutorial steps. The headers should be set up but for some reason, it's not working as expected.

![image](https://user-images.githubusercontent.com/1482075/219021007-4f91b1d7-b62e-400c-9f2c-9dfcaffbe9d9.png)
